.TH libcommoner 3 "November 13, 2018" "" "Programmer's Manual"
.SH NAME
libcommoner \- general purpose library
.SH SYNOPSIS
\fB#include <libcommoner.h>\fR

.SH DESCRIPTION

.SS "Macros"

.SS "Inline Functions"

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBchar cpeek(const char *\fR\fIc\fP\fB, const char *\fR\fIs\fP\fB, const short \fR\fIfwd\fP\fB);\fR"
.br
.ti -1c

.\" intlen
.RI "\fBint intlen(int\fR \fIn\fP\fB);\fR"
.ti -1c
.RI "\fBint intlenc(const int\fR \fIn\fP\fB);\fR"
.ti -1c
.RI "\fBsize_t intlenm(int\fR \fIn\fP\fB);\fR"
.ti -1c

.\" reverse
.RI "\fBvoid rev(char *\fR\fIs\fP\fB);\fR"
.ti -1c
.RI "\fBchar *revp(const char *\fR\fIs\fP\fB);\fR"
.ti -1c
.RI "\fBvoid revn(char *\fR\fIs\fP\fB, size_t\fR \fIn\fP\fB);\fR"
.ti -1c

.\" itoa
.RI "\fBvoid itoa(char *\fR\fIdest\fP\fB, int\fR \fIsrc\fP\fB);\fR"
.ti -1c
.RI "\fBchar *itoap(int\fR \fIsrc\fP\fB);\fR"
.ti -1c

.\" concat


.SH VERSIONS

If you come across a system that libcommoner either doesn't work or misbehaves on, please inform me <amagura28*gmail*>, be sure to include the output from \fBuname -a\fR and the version of libcommoner you are trying to use.

.SS Linux

This library was built on a system running Linux 4.xx.xx, but should run on most Linux systems irrespective of kernel version.

.SS BSD

Libcommoner should work on BSD systems (particularly FreeBSD), but I have not tested it in any official capacity.

.SS MSDOS/Windows

Libcommoner does not explicitly support Microsoft systems, but patches are welcome.
